### ISSUE TITLE
Amp\Parallel\Worker\enqueue: "Process has already been started."

### ISSUE THREAD

**Issue by enumag** [amphp/parallel#110]
I reworked a part of my application to use `amphp/parallel` in order to not block the main loop with those operations. However the `enqueue()` function sometimes randomly fails with a "Process has already been started." error.

Here is the relevant part of the stack trace:

```
#0 ...vendor/amphp/parallel/lib/Context/Process.php(191): Amp\Process\Process->start()
#1 [internal function]: Amp\Parallel\Context\Process->Amp\Parallel\Context\{closure}()
#2 ...vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#3 ...vendor/amphp/amp/lib/functions.php(75): Amp\Coroutine->__construct()
#4 ...vendor/amphp/parallel/lib/Context/Process.php(204): Amp\call()
#5 ...vendor/amphp/parallel/lib/Worker/Internal/WorkerProcess.php(39): Amp\Parallel\Context\Process->start()
#6 [internal function]: Amp\Parallel\Worker\Internal\WorkerProcess->Amp\Parallel\Worker\Internal\{closure}()
#7 ...vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#8 ...vendor/amphp/amp/lib/functions.php(75): Amp\Coroutine->__construct()
#9 ...vendor/amphp/parallel/lib/Worker/Internal/WorkerProcess.php(51): Amp\call()
#10 ...vendor/amphp/parallel/lib/Worker/TaskWorker.php(105): Amp\Parallel\Worker\Internal\WorkerProcess->start()
#11 [internal function]: Amp\Parallel\Worker\TaskWorker->Amp\Parallel\Worker\{closure}()
#12 ...vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#13 ...vendor/amphp/amp/lib/functions.php(75): Amp\Coroutine->__construct()
#14 ...vendor/amphp/parallel/lib/Worker/TaskWorker.php(135): Amp\call()
#15 ...vendor/amphp/parallel/lib/Worker/DefaultPool.php(152): Amp\Parallel\Worker\TaskWorker->enqueue()
#16 ...vendor/amphp/parallel/lib/Worker/functions.php(42): Amp\Parallel\Worker\DefaultPool->enqueue()
#17 ...src/...MyCode.php(71): Amp\Parallel\Worker\enqueue()
```

**Comment by enumag** [comment]
After diving a bit deeper into it the problem is that the process has already ended.

`Process::isRunning()` will return [false](https://github.com/amphp/process/blob/a9823125177bf8247af7cde28c24e511bc4260c0/lib/Process.php#L226-L229) but `Process::start()` will still [fail](https://github.com/amphp/process/blob/a9823125177bf8247af7cde28c24e511bc4260c0/lib/Process.php#L103-L105). Because of that [this](https://github.com/amphp/parallel/blob/7f00b8effb4fb439176aba0fa392abd120cbd952/lib/Worker/TaskWorker.php#L104-L106) does not work.

I'd like to send a PR with a fix but I'm not exactly certain what's the intended behavior.

**Comment by enumag** [comment]
bump - this bug is kinda critical and completely breaks amp/parallel for me. Please tell me how to proceed.

**Comment by trowski** [comment]
Once run, a process instance should not be able to be restarted. A `hasStarted()` (or similar) method could be added to `Process`.

That being said, the first time `$this->context->start()` is invoked, it should throw, no? `Worker::isRunning()` should return false after the `enqueue()` call fails. Perhaps the issue is that the work is put back in the pool when it shouldn't be.

**Comment by enumag** [comment]
> That being said, the first time `$this->context->start()` is invoked, it should throw, no?

Why? :thinking:

**Comment by trowski** [comment]
> Why? 🤔

I meant if the worker fails to start.

**Comment by enumag** [comment]
> Perhaps the issue is that the worker instance is put back in the pool when it shouldn't be.

Why shouldn't a worker instance be put back into the pool once it finished doing it's job? A worker is supposed to be able to handle repeated `enqueue` calls, right?


> Once run, a process instance should not be able to be restarted.

Okay. So `Amp\Process\Process` should be thrown away when finished.

So the question is, should `\Amp\Parallel\Context\Process` be able to restart? At the moment it's creating a Process instance [at the end of __construct()](https://github.com/amphp/parallel/blob/7f00b8effb4fb439176aba0fa392abd120cbd952/lib/Context/Process.php#L145).
- If it is supposed to restart then it shouldn't do that and only create the `Amp\Process\Process` instance when `start()` is called.
- If it isn't supposed to restart then I'm not sure how to handle it since `TaskWorker::__construct()` requires a Context.

**Comment by trowski** [comment]
If the process crashed, the worker instance should not be put back in the pool. Looking at the code though, this is handled and crashed workers are removed from the pool.

No, `Amp\Parallel\Context\Process` also should not be able to restart.

`TaskWorker::__construct()` should always be given a new `Context` object that has not been started.

Could you give me more context on what you're doing? I'm a little confused on how this is happening.

**Comment by enumag** [comment]
> Could you give me more context on what you're doing? I'm a little confused on how this is happening.

Certainly. I have `amphp/http-server` listening on a port. Some of the RequestHandlers are supposed to generate a PDF. Since this could block the main loop, I extracted this to a custom `DocumentTask` which implements `Amp\Parallel\Worker\Task`. The RequestHandler handles authentication, created a DocumentTask, calls `$file = yield enqueue($task);` and then it creates a Response from the returned $file ($file is my own class which has $filename and $content).

If I open several tabs for different documents at the same time, they all succeed without a problem. But as soon as one of the documents is finished then any new documents will fail to generate because a Worker is used for a second time which causes the bug I described.

**Comment by enumag** [comment]
> `TaskWorker::__construct()` should always be given a new `Context` object that has not been started.

You're confusing me. If this is true then it means that a Worker can never be used repeatedly (since Worker requires Context in constructor and not in enqueue method).

**Comment by enumag** [comment]
Or maybe the `\Amp\Process\Process` was not supposed to finish? I'm not sure.

**Comment by enumag** [comment]
Or maybe the `\Amp\Process\Process` wasn't supposed to finish? :thinking:

**Comment by trowski** [comment]
> If this is true then it means that a Worker can never be used repeatedly either (since Worker requires Context in constructor and not in enqueue method). This goes against my understanding of a "worker". 🤔

Once a `TaskWorker` object is created, it can be used repeatedly. That is, `TaskWorker::enqueue()` can be called multiple times. The context executing `TaskRunner::run()` will continue to run, waiting for new `Task` objects to be sent to it. 

> The question is if a Worker can call `Context::start()` repeatedly on the same Context instance. Are you really sure that this isn't allowed?

No, `Context::start()` should only be called once. I'm very sure.

> Or maybe the `\Amp\Process\Process` wasn't supposed to finish? 🤔

I'm guessing that the process is crashing for some reason after returning the PDF. Any ideas why the process might exit?

I did notice a bug in how `TaskWorker` reported if it was running or not, which would cause a crashed worker to be reused. I fixed it in ad91aafb0ffd27ddaf5da6d4fb7b511b1f5b0248 in the `issue-110` branch. Can you try using `amphp/parallel": "dev-issue-110 as 1.3"` and let me know if that changes anything?

**Comment by enumag** [comment]
> I'm guessing that the process is crashing for some reason after returning the PDF. Any ideas why the process might exit?

No idea whatsoever. My task returned the $file instance which was successfully serialized and made it to the main loop process.

>  Can you try using `"amphp/parallel": "dev-issue-110 as 1.3"` and let me know if that changes anything?

Nope, nothing changed. Still the same problem (and I had to re-apply the `?? []` fix in `\Amp\Parallel\Sync\flattenThrowableBacktrace`).

**Comment by trowski** [comment]
> Nope, nothing changed. Still the same problem (and I had to re-apply the `?? []` fix in `\Amp\Parallel\Sync\flattenThrowableBacktrace`).

That doesn't make sense, since I branched from master. Make sure sure you got the correct branch.

**Comment by enumag** [comment]
Sorry, I used `composer install` instead of `composer update` :man_facepalming:. It works fine now. Still if there is some problem with my workers crashing then I'd like to know why...

**Comment by enumag** [comment]
What is the current behavior? Is a crashed worker silently removed from the pool? Or would it throw some exception?

**Comment by trowski** [comment]
> Still if there is some problem with my workers crashing then I'd like to know why...

Me too. Any code you could provide me would be helpful. Specifically the `DocumentTask` class would be interesting.

> What is the current behavior? Is a crashed worker silently removed from the pool? Or would it throw some exception?

Yes, it's removed silently. Not exactly sure how to handle it, since the are various reasons a worker could crash (running out of memory), which is recoverable by starting another worker, but it would be nice to know that's happening. Maybe `trigger_error` and issue a warning?

**Comment by enumag** [comment]
> Yes, it's removed silently. Not exactly sure how to handle it, since the are various reasons a worker could crash (running out of memory), which is recoverable by starting another worker, but it would be nice to know that's happening. Maybe `trigger_error` and issue a warning?

I'd definitely like to have the problem appear in my monolog Logger. `trigger_error` would work for that purpose I think.

> Me too. Any code you could provide me would be helpful. Specifically the DocumentTask class would be interesting.

The DocumentTask itself isn't doing much. It just calls some service from the DI container. The task needs database and other things so I had to go through the whole process of creating Symfony Kernel, boot it, get a service from the container and delegate the work. The created Container is saved in `Amp\Parallel\Worker\Environment` so that it can be reused by subsequent calls to the same worker - this is why I'd like it to work. If the worker is crashing then it means the Kernel is booted again and again for each task... You can have a glimpse at the Task class [here](https://gist.github.com/enumag/d43a6d225a8b54f5196eae0c796c26c3) but I can't share all the related code.

**Comment by enumag** [comment]
@trowski I tried to look into why the worker process exited. It seems it just naturally reached the end of the [process-runner.php](https://github.com/amphp/parallel/blob/master/lib/Context/Internal/process-runner.php) file. Is there something that is supposed to keep the process alive? If there is, then it doesn't seem work...

**Comment by trowski** [comment]
> I'd definitely like to have the problem appear in my monolog Logger. trigger_error would work for that purpose I think.

I pushed another commit to the `issue-110` branch. Please update and see what sort of errors land in your log.

> How is it supposed to work?

The context is running an instance of [`TaskRunner`](https://github.com/amphp/parallel/blob/issue-110/lib/Worker/TaskRunner.php), which is a simple loop that receives `Task` objects from the parent, looping until a non-`Task` is received. (Well, actually `Job` objects, but that's an internal detail.) It's really not complicated.

> As far as I can tell the process didn't crash but rather naturally ended.

When process-runner.php ends normally, is it ending by sending an exception back to the parent? I'm wondering if some component you're using is failing after successfully generating the PDF.

**Comment by enumag** [comment]
> I pushed another commit to the issue-110 branch. Please update and see what sort of errors land in your log.

Thanks, I'll check if the trigger error lands in my log.

> The context is running an instance of TaskRunner, which is a simple loop that receives Task objects from the parent, looping until a non-Task is received. (Well, actually Job objects, but that's an internal detail.) It's really not complicated.

Thanks for explaining, I'll try again to see if I can figure something out.

> When process-runner.php ends normally, is it ending by sending an exception back to the parent? I'm wondering if some component you're using is failing after successfully generating the PDF.

As far as I can tell, no... but maybe I missed something. I'll let you know in a day or two when I get back to it.

Thanks for your advice!

**Comment by enumag** [comment]
Okay, now `enqueue()` triggers a warning which indeed makes it to log. I'll try to find out how this happened.

```
User Warning: Worker in pool crashed with exception on shutdown: User Warning: Worker in pool exited unexpectedly with code -1
```

**Comment by enumag** [comment]
However I thought that this was a just warning and Amphp should recover from it, right? Well it didn't recover:

```
error: Amp\Parallel\Sync\ChannelException: The channel closed unexpectedly. Did the context die? in .../vendor/amphp/parallel/lib/Sync/ChannelledStream.php:74
Stack trace:
#0 [internal function]: Amp\Parallel\Sync\ChannelledStream->Amp\Parallel\Sync\{closure}()
#1 .../vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#2 .../vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#3 .../vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve()
#4 .../vendor/amphp/byte-stream/lib/ResourceInputStream.php(198): Amp\Deferred->resolve()
#5 .../vendor/amphp/byte-stream/lib/ResourceInputStream.php(182): Amp\ByteStream\ResourceInputStream->free()
#6 .../vendor/amphp/parallel/lib/Sync/ChannelledSocket.php(68): Amp\ByteStream\ResourceInputStream->close()
#7 .../vendor/amphp/parallel/lib/Context/Process.php(398): Amp\Parallel\Sync\ChannelledSocket->close()
#8 .../vendor/amphp/parallel/lib/Worker/Internal/WorkerProcess.php(57): Amp\Parallel\Context\Process->kill()
#9 .../vendor/amphp/parallel/lib/Worker/TaskWorker.php(63): Amp\Parallel\Worker\Internal\WorkerProcess->kill()
#10 [internal function]: Amp\Parallel\Worker\TaskWorker::Amp\Parallel\Worker\{closure}()
#11 {main}

Next Amp\Parallel\Context\ContextException: The process stopped responding, potentially due to a fatal error or calling exit in .../vendor/amphp/parallel/lib/Context/Process.php:228
Stack trace:
#0 [internal function]: Amp\Parallel\Context\Process->Amp\Parallel\Context\{closure}()
#1 .../vendor/amphp/amp/lib/Coroutine.php(115): Generator->throw()
#2 .../vendor/amphp/amp/lib/Failure.php(33): Amp\Coroutine->Amp\{closure}()
#3 .../vendor/amphp/amp/lib/Internal/Placeholder.php(143): Amp\Failure->onResolve()
#4 .../vendor/amphp/amp/lib/Internal/Placeholder.php(177): Amp\Coroutine->resolve()
#5 .../vendor/amphp/amp/lib/Coroutine.php(137): Amp\Coroutine->fail()
#6 .../vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#7 .../vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve()
#8 .../vendor/amphp/byte-stream/lib/ResourceInputStream.php(198): Amp\Deferred->resolve()
#9 .../vendor/amphp/byte-stream/lib/ResourceInputStream.php(182): Amp\ByteStream\ResourceInputStream->free()
#10 .../vendor/amphp/parallel/lib/Sync/ChannelledSocket.php(68): Amp\ByteStream\ResourceInputStream->close()
#11 .../vendor/amphp/parallel/lib/Context/Process.php(398): Amp\Parallel\Sync\ChannelledSocket->close()
#12 .../vendor/amphp/parallel/lib/Worker/Internal/WorkerProcess.php(57): Amp\Parallel\Context\Process->kill()
#13 .../vendor/amphp/parallel/lib/Worker/TaskWorker.php(63): Amp\Parallel\Worker\Internal\WorkerProcess->kill()
#14 [internal function]: Amp\Parallel\Worker\TaskWorker::Amp\Parallel\Worker\{closure}()
#15 {main}  
Makefile:6: recipe for target 'serve' failed
make: *** [serve] Error 1

```

**Comment by enumag** [comment]
I added some debug code into TaskRunner too to find out what happened. Turns out that `TaskRunner::run()` indeed threw an exception. Here are the details I was able to get:

```
Amp\\Parallel\\Sync\\ChannelException: The channel closed unexpectedly. Did the context die? in .../vendor/amphp/parallel/lib/Sync/ChannelledStream.php on line 74

Call Stack:
    4.9204   29819032   1. Amp\\ByteStream\\ResourceInputStream->__destruct() .../vendor/amphp/byte-stream/lib/ResourceInputStream.php:0
    4.9205   29819032   2. Amp\\ByteStream\\ResourceInputStream->free() .../vendor/amphp/byte-stream/lib/ResourceInputStream.php:259
    4.9205   29819032   3. Amp\\Deferred->resolve(???) .../vendor/amphp/byte-stream/lib/ResourceInputStream.php:198
    4.9205   29819032   4. {anonymous-class:.../vendor/amphp/amp/lib/Deferred.php:22-27}->resolve(???) .../vendor/amphp/amp/lib/Deferred.php:52
    4.9205   29819032   5. Amp\\Coroutine->Amp\\{closure:.../vendor/amphp/amp/lib/Coroutine.php:91-148}(???, ???) .../vendor/amphp/amp/lib/Internal/Placeholder.php:149
    4.9207   29825264   6. Amp\\Coroutine->fail(???) .../vendor/amphp/amp/lib/Coroutine.php:137
    4.9209   29830112   7. Amp\\Coroutine->resolve(???) .../vendor/amphp/amp/lib/Internal/Placeholder.php:177
    4.9210   29830112   8. Amp\\Failure->onResolve(???) .../vendor/amphp/amp/lib/Internal/Placeholder.php:143
    4.9210   29830112   9. Amp\\Coroutine->Amp\\{closure:.../vendor/amphp/amp/lib/Coroutine.php:91-148}(???, ???) .../vendor/amphp/amp/lib/Failure.php:33
    4.9210   29830112  10. Generator->throw(???) .../vendor/amphp/amp/lib/Coroutine.php:115
```

**Comment by enumag** [comment]
@trowski Okay... it seems the entire problem was caused by me calling the `wait()` function at one point in the Task (it was a part of code that I was planning to refactor later). It seems that starting another `Loop` while one is running already can cause VERY unexpected behavior.

My suggestion what to do here:

1. Fix `enqueue()` to be able to recover after worker crash (https://github.com/amphp/parallel/issues/110#issuecomment-613330370).
2. Have `Loop::run()` throw an exception if there already is an active Loop.

**Comment by trowski** [comment]
Error trigger tagged as part of `v1.4.0`.

We're still sorting out how we should handle nested calls to `Promise\wait()`, but that's tangental to this issue and not related to this repo.
